from typing import Generator, Callable
import re

def generator_numbers(text: str) -> Generator[float, None, None]:
    # Use regular expressions to find all numbers in the text
    match = re.findall(r"\d+\.\d+|\d+", text)
    # Yield each number as a float
    for number in match:
        yield float(number)


def sum_profit(text: str, func: Callable):
    summ = 0
    # Iterate over the numbers generated by the provided function
    for number in func(text):
        # Add each number to the total sum
        summ += float(number)
    return summ


text = "Загальний дохід працівника складається з декількох частин: 1000.01 як основний дохід, доповнений додатковими надходженнями 27.45 і 324.00 доларів."
total_income = sum_profit(text, generator_numbers)
# print(f"Загальний дохід: {total_income}")

print(total_income) 
